### ISSUE TITLE
Dashboard still shows #rmu-general and #rmu-public, should show just #rmu

### ISSUE THREAD

**Issue by carols10cents** [mendicant-original/university-web#50]
Might fix this if I get a second, do tiny bug fixes count towards my s5-e4? ;)

**Comment by practicingruby** [comment]
If you collect many bug fixes together, yes.  But that's actually a more complicated thing to fix than you might think.  People may want to reference the general and public logs, and so what we really need is a way to let individual users hide or show the channels they have access to.

**Comment by jordanbyron** [comment]
There are several tickets in pivotal concerning this issue:

https://www.pivotaltracker.com/story/show/9687541
https://www.pivotaltracker.com/story/show/9687851

**Comment by smiller** [comment]
I may be the one misreading, but I see a different initial problem: right now, my user doesn't have access to #rmu on my dashboard – does anyone? – so even if the showing and hiding mechanism of 9687541 existed. I still wouldn't be able to see the current public IRC channel #rmu on my dashboard, though I would be able to hide the now-defunct #rmu-public and #rmu-general.

Wouldn't adding #rmu to chat_channels, and adding that channel to every user's chat_channel_memberships, solve that problem?  It looks like a data fix rather than a code fix, but it's something that someone in the presumably much smaller body of people who have access to the production database could do quite simply.

**Comment by jordanbyron** [comment]
You are correct, and I will run a quick query to add #rmu to those who don't have it.

In the future we want these public channels to be automatically available to everyone. I've created a ticket for that in pivotal:

https://www.pivotaltracker.com/story/show/9687851
