### ISSUE TITLE
Nested comments

### ISSUE THREAD

**Issue by pellegrino** [mendicant-original/university-web#76]
When there are many comments at a submission, it is hard to identify whether a message it is related or no to another.  I think if the comments were nested, it would be easier to read them. 

What you guys think about it?

**Comment by practicingruby** [comment]
Some form of threading would be nice, I worry about deep nesting because our comments can be long and involve long code samples, but maybe some sort of 'in reply to' link would be useful?

**Comment by pellegrino** [comment]
Yeah, you're right. I think the 'in reply to' link would help a lot by itself. Maybe even making threading irrelevant.

**Comment by practicingruby** [comment]
So here's how I think that could work:
- Number each comment in the thread (starting with #1 as the first one).
- Make it possible to get links to individual comments by just using an in-page anchor. So that means that the comment should be still displayed in the thread, but that you'd get scrolled to its location upon hitting that URL.
- Add a reply button to each comment that either drops down a text box directly or scrolls you to the text box at the bottom of the page.
- Add the words "in reply to comment #xyz" after the words "User X made a comment" in the status bar above the comment, with a link to the comment it is in reply to.

Jordan can help with the mechanics if you want to work on this, but that's the rough idea I have in mind.

**Comment by pellegrino** [comment]
That sounds good. As my s7-e4 i will be touching RMU to add Github repositories at users profiles. After that, i will give a go on this. Just wanted to add this issue here so i don't forget and other people could give their feedback about it.

**Comment by practicingruby** [comment]
@pellegrino: Would you be open to letting someone else work on this feature for their s7-e4 if they're looking for something? If so, please post it to the session mailing list. It's a good idea.

**Comment by pellegrino** [comment]
Sure! I will do it right now. :)

**Comment by andrewhr** [comment]
Can I take that? :)

**Comment by pellegrino** [comment]
I think so! Nobody has claimed neither here or at the mailing list :)
Feel free to do it.

**Comment by jordanbyron** [comment]
Merged: https://github.com/rmu/university-web/pull/88
